### ISSUE TITLE
Run on android

### ISSUE THREAD

**Issue by Kadanza** [raryelcostasouza/JAutosub#1]
It is possible to run autosub on android?

**Comment by raryelcostasouza** [comment]
Sorry but I'm myself never tried. One detail is that for converting the different audio/video input formats autosub uses external ffmpeg binary... so you would need to get a ARM release of the ffmpeg binary. Apart from that you might need to make some adaptations on the python code for compatibility with android...

Good  luck,

**Comment by raryelcostasouza** [comment]
Probably good to consult with the actual autosub developer at https://github.com/agermanidis/autosub... this repository of mine is just for a simple Java GUI that I developed for running autosub.
